package:
  name: vtk
  version: 7.1.0

source:
  git_url: https://github.com/Kitware/VTK.git
  git_rev: master
  #url: http://www.vtk.org/files/release/7.1/VTK-7.1.0.tar.gz
  #fn:  VTK-7.1.0.tar.gz

build:
  number: 3                                   [linux,osx]
  has_prefix_files:                           [win]
    - Lib/site-packages/vtk/__init__.py       [win]

requirements:
  build:
    - cmake
    - python    <3
  run:
    - python    <3

test:
  imports:
    - vtk
    - vtk.vtkChartsCore
    - vtk.vtkCommonCore
    - vtk.vtkFiltersCore
    - vtk.vtkFiltersGeneric
    - vtk.vtkGeovisCore
    - vtk.vtkFiltersHybrid
    - vtk.vtkIOCore
    - vtk.vtkImagingCore
    - vtk.vtkInfovisCore
    - vtk.vtkRenderingCore
    - vtk.vtkViewsCore
    - vtk.vtkRenderingVolume
    - vtk.vtkInteractionWidgets

about:
  home: http://www.vtk.org/
  license: BSD
  summary: VTK is an open-source, freely available software system for 3D computer graphics
